version: '3.8'

services:

  app:
    build:
      context: .
    restart: always
    container_name: baryga_shop_app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./documents:/documents/
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:16.2-alpine
    container_name: db_baryga_shop_app
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - .postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"


  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build:
      context: .
    container_name: celery_baryga_shop_app
    command: celery -A src.tasks.celery_task:celery worker --loglevel=info
    volumes:
      - ./documents:/documents/
    depends_on:
      - rabbitmq


  migrate:
    build:
      context: .
    restart: on-failure
    container_name: alembic_baryga_shop_app
    command: alembic upgrade head
    depends_on:
      - db
      - app