"""change orderItem model

Revision ID: d6ff7928df8d
Revises: 7049cb26eaf0
Create Date: 2024-06-24 11:06:00.761992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ff7928df8d'
down_revision: Union[str, None] = '7049cb26eaf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_item', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_item', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
