"""add column total_price in OrderItem

Revision ID: ebb1b40e51dc
Revises: d6ff7928df8d
Create Date: 2024-06-25 11:23:30.015099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb1b40e51dc'
down_revision: Union[str, None] = 'd6ff7928df8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('total_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'total_price')
    # ### end Alembic commands ###
